// ============================================================
// BlogFlow AI - Mock/Demo Data
// All data below is clearly demo data for UI development.
// It will be replaced by real database queries in production.
// ============================================================

import {
  Website, Research, Blog, QualityReport, Approval,
  Integration, PublishingRecord, AutomationRule, AnalyticsData,
  User, WebsiteAnalysis,
} from '@/types';

export const DEMO_USER: User = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex@blogflow.ai',
  avatar: undefined,
  role: 'admin',
  createdAt: '2025-01-15T10:00:00Z',
  updatedAt: '2025-09-20T14:30:00Z',
};

export const DEMO_WEBSITES: Website[] = [
  {
    id: 'web-1',
    userId: 'user-1',
    name: 'TechVerse Blog',
    url: 'https://techverse.blog',
    niche: 'Technology',
    audience: 'Tech enthusiasts and developers',
    tone: 'professional',
    keywords: ['AI', 'machine learning', 'web development', 'cloud computing'],
    excludedTopics: ['cryptocurrency', 'gambling'],
    connectionStatus: 'connected',
    blogsGenerated: 24,
    lastActivity: '2025-09-28T15:30:00Z',
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: '2025-09-28T15:30:00Z',
  },
  {
    id: 'web-2',
    userId: 'user-1',
    name: 'HealthWise Hub',
    url: 'https://healthwisehub.com',
    niche: 'Health & Wellness',
    audience: 'Health-conscious adults',
    tone: 'friendly',
    keywords: ['nutrition', 'fitness', 'mental health', 'wellness tips'],
    excludedTopics: ['extreme diets', 'unverified supplements'],
    connectionStatus: 'connected',
    blogsGenerated: 18,
    lastActivity: '2025-09-27T12:00:00Z',
    createdAt: '2025-04-15T09:00:00Z',
    updatedAt: '2025-09-27T12:00:00Z',
  },
  {
    id: 'web-3',
    userId: 'user-1',
    name: 'StartupLaunch',
    url: 'https://startuplaunch.io',
    niche: 'Business & Startups',
    audience: 'Entrepreneurs and startup founders',
    tone: 'authoritative',
    keywords: ['startups', 'venture capital', 'business strategy', 'growth hacking'],
    excludedTopics: ['MLM', 'get-rich-quick'],
    connectionStatus: 'pending',
    blogsGenerated: 5,
    lastActivity: '2025-09-25T08:00:00Z',
    createdAt: '2025-07-20T11:00:00Z',
    updatedAt: '2025-09-25T08:00:00Z',
  },
];

export const DEMO_WEBSITE_ANALYSIS: WebsiteAnalysis = {
  id: 'analysis-1',
  websiteId: 'web-1',
  detectedNiche: 'Technology & Software Development',
  targetAudience: 'Software developers, tech enthusiasts, and IT professionals aged 25-45',
  existingContentSummary: 'The website contains 45 published articles primarily covering web development frameworks, AI/ML tutorials, and cloud computing guides. Content averages 1,800 words per article with a professional yet approachable tone.',
  writingStyle: 'Professional, technically accurate, with code examples and practical applications. Uses H2/H3 hierarchy consistently. Includes introductory context before diving into technical details.',
  contentOpportunities: [
    'Edge computing and serverless architecture guides',
    'AI-powered development tools comparison',
    'DevOps best practices and CI/CD pipelines',
    'Web performance optimization techniques',
    'Emerging JavaScript frameworks deep dives',
  ],
  analyzedAt: '2025-09-20T10:00:00Z',
};

export const DEMO_RESEARCH: Research[] = [
  {
    id: 'research-1',
    websiteId: 'web-1',
    topic: 'AI-Powered Code Generation Tools in 2025',
    category: 'Technology',
    targetAudience: 'Software developers',
    keywords: ['AI code generation', 'GitHub Copilot', 'coding assistants', 'developer tools'],
    discoveredTopics: [
      {
        id: 'topic-1',
        title: 'The Rise of AI Code Assistants: A Comprehensive Comparison',
        description: 'An in-depth analysis of the leading AI-powered code generation tools, comparing features, accuracy, and developer experience.',
        searchIntent: 'informational',
        suggestedKeywords: ['AI coding tools comparison', 'best AI code assistant 2025'],
        insights: [
          'AI code assistants have seen 300% adoption growth in the past year',
          'GitHub Copilot leads market share at 45%',
          'Code quality concerns remain the primary barrier to adoption',
        ],
        sources: [
          { title: 'State of AI-Assisted Development 2025', url: 'https://example.com/ai-dev-report', snippet: 'Survey of 10,000 developers reveals...', relevanceScore: 95 },
          { title: 'AI Code Generation Benchmark Results', url: 'https://example.com/benchmark', snippet: 'Comprehensive benchmarks across 5 major tools...', relevanceScore: 90 },
        ],
        selected: true,
      },
      {
        id: 'topic-2',
        title: 'How AI Code Generation Is Changing Software Architecture',
        description: 'Exploring how AI-generated code is influencing software design patterns and architectural decisions.',
        searchIntent: 'informational',
        suggestedKeywords: ['AI software architecture', 'code generation impact'],
        insights: [
          'Teams using AI tools report 40% faster prototyping',
          'New architectural patterns emerging from AI-generated code',
        ],
        sources: [
          { title: 'Software Architecture in the AI Era', url: 'https://example.com/arch-ai', snippet: 'A study on architectural shifts...', relevanceScore: 85 },
        ],
        selected: false,
      },
      {
        id: 'topic-3',
        title: 'Best Practices for Integrating AI Code Assistants in Your Workflow',
        description: 'Practical guide on effectively using AI coding tools in daily development workflows without sacrificing code quality.',
        searchIntent: 'how-to',
        suggestedKeywords: ['AI coding best practices', 'developer workflow AI'],
        insights: [
          'Code review processes need updating for AI-generated code',
          '75% of developers use AI tools for boilerplate code',
          'Testing AI-generated code requires specific strategies',
        ],
        sources: [
          { title: 'AI Developer Workflow Guide', url: 'https://example.com/workflow', snippet: 'Best practices from leading teams...', relevanceScore: 88 },
          { title: 'Code Quality with AI Tools', url: 'https://example.com/quality-ai', snippet: 'Maintaining standards with AI assistance...', relevanceScore: 82 },
        ],
        selected: false,
      },
    ],
    status: 'completed',
    createdAt: '2025-09-25T10:00:00Z',
    updatedAt: '2025-09-25T10:30:00Z',
  },
  {
    id: 'research-2',
    websiteId: 'web-2',
    topic: 'Mindfulness and Mental Health Benefits',
    category: 'Health & Wellness',
    targetAudience: 'Health-conscious adults',
    keywords: ['mindfulness', 'mental health', 'meditation', 'stress reduction'],
    discoveredTopics: [
      {
        id: 'topic-4',
        title: 'Science-Backed Benefits of Daily Mindfulness Practice',
        description: 'A comprehensive look at the latest research on how mindfulness meditation impacts mental and physical health.',
        searchIntent: 'informational',
        suggestedKeywords: ['mindfulness benefits research', 'daily meditation science'],
        insights: [
          'Studies show 30% reduction in anxiety with regular practice',
          'Mindfulness changes brain structure measurably within 8 weeks',
        ],
        sources: [
          { title: 'Mindfulness Research Digest 2025', url: 'https://example.com/mindfulness-research', snippet: 'Latest neuroscience findings on meditation...', relevanceScore: 92 },
        ],
        selected: true,
      },
    ],
    status: 'completed',
    createdAt: '2025-09-26T09:00:00Z',
    updatedAt: '2025-09-26T09:45:00Z',
  },
];

export const DEMO_BLOGS: Blog[] = [
  {
    id: 'blog-1',
    websiteId: 'web-1',
    websiteName: 'TechVerse Blog',
    researchId: 'research-1',
    title: 'The Rise of AI Code Assistants: A Comprehensive Comparison for 2025',
    subtitle: 'How AI-powered tools are transforming the way developers write, review, and ship code',
    slug: 'ai-code-assistants-comparison-2025',
    content: `## Introduction\n\nArtificial intelligence has fundamentally transformed software development. In 2025, AI code assistants are no longer experimental tools — they are essential components of modern development workflows. From auto-completing complex functions to generating entire modules, these tools are reshaping how developers approach coding challenges.\n\n## What Are AI Code Assistants?\n\nAI code assistants are machine learning-powered tools that help developers write code faster and with fewer errors. They analyze context from your codebase, understand natural language prompts, and generate relevant code suggestions in real-time.\n\n## Top AI Code Assistants in 2025\n\n### GitHub Copilot\n\nGitHub Copilot remains the market leader with a 45% market share. Powered by advanced language models, it offers:\n\n- Real-time code suggestions across 20+ languages\n- Context-aware completions based on your entire repository\n- Natural language to code generation\n- Integrated chat for code explanations and debugging\n\n### Amazon CodeWhisperer\n\nAmazon's offering has gained significant traction, especially among AWS users:\n\n- Deep integration with AWS services\n- Security scanning built-in\n- Reference tracking for open-source code\n- Competitive pricing for enterprise teams\n\n### Google's AI Coding Tools\n\nGoogle has expanded its AI coding capabilities with tools that integrate seamlessly into the development ecosystem.\n\n## Impact on Developer Productivity\n\nStudies show that developers using AI code assistants experience:\n\n- **40% faster** prototyping and initial development\n- **25% reduction** in bugs during initial coding\n- **60% less time** spent on boilerplate code\n- **35% improvement** in overall developer satisfaction\n\n## Best Practices for Using AI Code Assistants\n\n1. **Always review generated code** — AI suggestions should be treated as drafts\n2. **Use clear, descriptive comments** — Better context leads to better suggestions  \n3. **Maintain your testing practices** — AI-generated code needs the same rigor\n4. **Learn prompt engineering** — The quality of your prompts directly affects output quality\n5. **Stay updated on tool capabilities** — These tools evolve rapidly\n\n## Conclusion\n\nAI code assistants have matured from novelty to necessity. The key is choosing the right tool for your workflow and using it as an enhancement to, not a replacement for, skilled development practices. As these tools continue to evolve, developers who master their use will have a significant competitive advantage.`,
    introduction: 'Artificial intelligence has fundamentally transformed software development...',
    conclusion: 'AI code assistants have matured from novelty to necessity...',
    faqs: [
      { question: 'Are AI code assistants replacing developers?', answer: 'No. AI code assistants are tools that augment developer capabilities. They handle repetitive tasks and boilerplate, allowing developers to focus on architecture, logic, and creative problem-solving.' },
      { question: 'Which AI code assistant is best for beginners?', answer: 'GitHub Copilot is generally recommended for beginners due to its intuitive integration with VS Code and comprehensive documentation.' },
      { question: 'How accurate are AI code suggestions?', answer: 'Accuracy varies by context and complexity. For straightforward code, accuracy can be 70-85%. Complex logic may require more developer oversight.' },
    ],
    metaTitle: 'AI Code Assistants 2025: Complete Comparison & Guide | TechVerse',
    metaDescription: 'Compare the top AI code assistants in 2025. Detailed analysis of GitHub Copilot, CodeWhisperer, and more. Discover which tool best fits your development workflow.',
    focusKeyword: 'AI code assistants',
    secondaryKeywords: ['code generation tools', 'GitHub Copilot', 'developer productivity'],
    tags: ['AI', 'coding tools', 'developer productivity', 'code generation'],
    category: 'Technology',
    imageSuggestions: [
      { description: 'Hero image showing a developer using AI code assistant', altText: 'Developer using AI-powered code assistant in modern IDE', placement: 'hero' },
      { description: 'Comparison chart of AI code assistants', altText: 'Feature comparison chart of top AI code assistants 2025', placement: 'mid-article' },
    ],
    references: ['https://example.com/ai-dev-report', 'https://example.com/benchmark'],
    status: 'pending_approval',
    wordCount: 1850,
    readingTime: 8,
    createdAt: '2025-09-25T11:00:00Z',
    updatedAt: '2025-09-26T09:00:00Z',
  },
  {
    id: 'blog-2',
    websiteId: 'web-2',
    websiteName: 'HealthWise Hub',
    researchId: 'research-2',
    title: 'Science-Backed Benefits of Daily Mindfulness Practice',
    subtitle: 'How just 10 minutes a day can transform your mental and physical health',
    slug: 'daily-mindfulness-benefits-science',
    content: `## Introduction\n\nIn our fast-paced world, mindfulness has emerged as a powerful tool for managing stress, improving focus, and enhancing overall well-being. But beyond the buzzwords, what does science actually say about the benefits of daily mindfulness practice?\n\n## What Is Mindfulness?\n\nMindfulness is the practice of intentionally focusing your attention on the present moment, acknowledging and accepting your thoughts, feelings, and bodily sensations without judgment.\n\n## The Science Behind Mindfulness\n\n### Brain Structure Changes\n\nResearch from leading neuroscience institutions has shown that regular mindfulness meditation physically changes brain structure. After just 8 weeks of consistent practice, MRI scans reveal:\n\n- **Increased gray matter density** in the hippocampus (learning and memory)\n- **Reduced amygdala size** (stress and fear responses)\n- **Enhanced prefrontal cortex activity** (decision-making and emotional regulation)\n\n### Mental Health Benefits\n\n- 30% reduction in anxiety symptoms\n- 25% improvement in depression scores\n- Better emotional regulation and resilience\n- Improved sleep quality\n\n### Physical Health Benefits\n\n- Lower blood pressure\n- Reduced inflammation markers\n- Improved immune function\n- Better pain management\n\n## How to Start a Daily Mindfulness Practice\n\n1. **Start with 5 minutes** — Consistency matters more than duration\n2. **Choose a regular time** — Morning or evening works best\n3. **Find a quiet space** — Minimize distractions\n4. **Focus on your breath** — The simplest and most effective anchor\n5. **Be patient** — Benefits accumulate over time\n\n## Conclusion\n\nThe evidence is clear: daily mindfulness practice offers significant, measurable benefits for both mental and physical health. The best part is that you don't need hours of meditation — even 10 minutes a day can make a meaningful difference.`,
    introduction: 'In our fast-paced world, mindfulness has emerged as a powerful tool...',
    conclusion: 'The evidence is clear: daily mindfulness practice offers significant benefits...',
    faqs: [
      { question: 'How long should I meditate each day?', answer: 'Research suggests that even 10 minutes of daily mindfulness practice can produce measurable benefits. Start with 5 minutes and gradually increase.' },
      { question: 'Can mindfulness replace therapy?', answer: 'Mindfulness is a complementary practice, not a replacement for professional mental health treatment. Consult a healthcare provider for serious mental health concerns.' },
    ],
    metaTitle: 'Science-Backed Mindfulness Benefits: Daily Practice Guide | HealthWise',
    metaDescription: 'Discover the science-backed benefits of daily mindfulness meditation. Learn how 10 minutes a day can reduce anxiety, improve focus, and boost overall health.',
    focusKeyword: 'mindfulness benefits',
    secondaryKeywords: ['daily meditation', 'mental health', 'stress reduction'],
    tags: ['mindfulness', 'meditation', 'mental health', 'wellness'],
    category: 'Health & Wellness',
    imageSuggestions: [
      { description: 'Person meditating in a peaceful setting', altText: 'Person practicing mindfulness meditation in nature', placement: 'hero' },
    ],
    references: ['https://example.com/mindfulness-research'],
    status: 'published',
    wordCount: 1200,
    readingTime: 5,
    createdAt: '2025-09-26T10:00:00Z',
    updatedAt: '2025-09-27T14:00:00Z',
  },
  {
    id: 'blog-3',
    websiteId: 'web-1',
    websiteName: 'TechVerse Blog',
    title: 'Building Scalable APIs with Next.js Route Handlers',
    subtitle: 'A practical guide to creating production-ready APIs with Next.js 14+',
    slug: 'scalable-apis-nextjs-route-handlers',
    content: `## Introduction\n\nNext.js Route Handlers provide a powerful, built-in solution for building APIs directly within your Next.js application. In this guide, we explore how to create scalable, maintainable API endpoints.\n\n## Getting Started\n\nRoute Handlers are defined in the app directory using the convention of creating route.ts files.\n\n## Conclusion\n\nNext.js Route Handlers offer a clean, integrated approach to building APIs that scale with your application.`,
    faqs: [],
    metaTitle: 'Building Scalable APIs with Next.js | TechVerse Blog',
    metaDescription: 'Learn how to build production-ready, scalable APIs using Next.js Route Handlers with TypeScript.',
    focusKeyword: 'Next.js API',
    secondaryKeywords: ['route handlers', 'REST API', 'TypeScript'],
    tags: ['Next.js', 'API', 'TypeScript', 'web development'],
    category: 'Technology',
    imageSuggestions: [],
    references: [],
    status: 'draft',
    wordCount: 450,
    readingTime: 2,
    createdAt: '2025-09-28T08:00:00Z',
    updatedAt: '2025-09-28T08:00:00Z',
  },
  {
    id: 'blog-4',
    websiteId: 'web-1',
    websiteName: 'TechVerse Blog',
    title: 'Understanding Edge Computing: A Developer\'s Guide',
    slug: 'understanding-edge-computing-guide',
    content: `## Introduction\n\nEdge computing brings computation closer to data sources, reducing latency and bandwidth usage. For developers, this means new architectural patterns and deployment strategies.\n\n## What Is Edge Computing?\n\nEdge computing processes data near its source rather than relying solely on centralized cloud servers.\n\n## Benefits for Developers\n\n- Reduced latency for real-time applications\n- Lower bandwidth costs\n- Improved data privacy\n- Better offline capabilities\n\n## Conclusion\n\nEdge computing represents a paradigm shift that developers need to understand and embrace.`,
    faqs: [
      { question: 'Is edge computing replacing cloud computing?', answer: 'No, edge computing complements cloud computing by handling time-sensitive processing locally while leveraging the cloud for heavy computation and storage.' },
    ],
    metaTitle: 'Edge Computing Guide for Developers | TechVerse Blog',
    metaDescription: 'A comprehensive guide to edge computing for developers. Learn about architecture patterns, deployment strategies, and practical use cases.',
    focusKeyword: 'edge computing',
    secondaryKeywords: ['CDN', 'serverless', 'low latency'],
    tags: ['edge computing', 'cloud', 'architecture', 'performance'],
    category: 'Technology',
    imageSuggestions: [],
    references: [],
    status: 'approved',
    wordCount: 320,
    readingTime: 2,
    createdAt: '2025-09-27T14:00:00Z',
    updatedAt: '2025-09-28T10:00:00Z',
  },
  {
    id: 'blog-5',
    websiteId: 'web-2',
    websiteName: 'HealthWise Hub',
    title: 'Nutrition Myths Debunked: What Science Really Says',
    slug: 'nutrition-myths-debunked-science',
    content: '## Introduction\n\nNavigating nutrition advice can be overwhelming. Let\'s separate fact from fiction using the latest scientific research.\n\n## Common Myths\n\n### Myth 1: Carbs Are the Enemy\n\nComplex carbohydrates are essential for brain function and physical energy.\n\n### Myth 2: You Need to Eat Every 2 Hours\n\nMeal timing is less important than overall daily nutrition quality.\n\n## Conclusion\n\nEvidence-based nutrition is about balance, not extremes.',
    faqs: [],
    metaTitle: 'Nutrition Myths vs Science | HealthWise Hub',
    metaDescription: 'Discover the truth behind common nutrition myths with evidence-based analysis.',
    focusKeyword: 'nutrition myths',
    secondaryKeywords: ['healthy eating', 'diet science', 'food facts'],
    tags: ['nutrition', 'health', 'diet', 'science'],
    category: 'Health & Wellness',
    imageSuggestions: [],
    references: [],
    status: 'scheduled',
    wordCount: 280,
    readingTime: 2,
    createdAt: '2025-09-24T10:00:00Z',
    updatedAt: '2025-09-26T16:00:00Z',
  },
  {
    id: 'blog-6',
    websiteId: 'web-3',
    websiteName: 'StartupLaunch',
    title: 'Securing Your First Round of Funding: A Complete Playbook',
    slug: 'securing-first-funding-round-playbook',
    content: '## Introduction\n\nRaising capital is one of the biggest challenges for early-stage startups. This guide covers everything from pitch preparation to term sheet negotiation.\n\n## Conclusion\n\nFunding is a milestone, not a destination. Focus on building a great product and the investment will follow.',
    faqs: [],
    metaTitle: 'First Funding Round Guide | StartupLaunch',
    metaDescription: 'Complete guide to securing your startup\'s first funding round. From pitch decks to term sheets.',
    focusKeyword: 'startup funding',
    secondaryKeywords: ['venture capital', 'seed round', 'pitch deck'],
    tags: ['funding', 'startup', 'venture capital', 'entrepreneurship'],
    category: 'Business & Startups',
    imageSuggestions: [],
    references: [],
    status: 'changes_requested',
    wordCount: 200,
    readingTime: 1,
    createdAt: '2025-09-22T10:00:00Z',
    updatedAt: '2025-09-25T11:00:00Z',
  },
];

export const DEMO_QUALITY_REPORTS: QualityReport[] = [
  {
    id: 'qr-1',
    blogId: 'blog-1',
    grammarScore: 92,
    readabilityScore: 85,
    seoScore: 88,
    overallScore: 88,
    issues: [
      { type: 'seo', severity: 'low', message: 'Meta description could be more compelling', suggestion: 'Add a call-to-action or unique value proposition' },
      { type: 'readability', severity: 'low', message: 'Some sentences exceed 25 words', suggestion: 'Break long sentences for better readability', location: 'Paragraph 3' },
      { type: 'structure', severity: 'medium', message: 'Consider adding more internal links', suggestion: 'Link to related articles within your site' },
    ],
    suggestions: [
      'Add 2-3 internal links to related technology articles',
      'Include a comparison table for quick reference',
      'Add author bio for E-E-A-T signals',
    ],
    keywordDensity: 1.8,
    headingStructure: 'good',
    contentOrganization: 'good',
    duplicateContentWarning: false,
    isSimulated: true,
    createdAt: '2025-09-25T11:30:00Z',
  },
];

export const DEMO_APPROVALS: Approval[] = [
  {
    id: 'approval-1',
    blogId: 'blog-1',
    blogTitle: 'The Rise of AI Code Assistants: A Comprehensive Comparison for 2025',
    status: 'pending',
    comments: [
      {
        id: 'comment-1',
        userId: 'user-1',
        userName: 'Alex Morgan',
        comment: 'Great article overall. Please verify the market share statistics before we approve.',
        createdAt: '2025-09-26T09:15:00Z',
      },
    ],
    createdAt: '2025-09-25T12:00:00Z',
  },
  {
    id: 'approval-2',
    blogId: 'blog-6',
    blogTitle: 'Securing Your First Round of Funding: A Complete Playbook',
    reviewerId: 'user-1',
    reviewerName: 'Alex Morgan',
    status: 'revision_requested',
    comments: [
      {
        id: 'comment-2',
        userId: 'user-1',
        userName: 'Alex Morgan',
        comment: 'The content is too brief. Please expand sections on pitch deck preparation and investor outreach.',
        createdAt: '2025-09-25T11:00:00Z',
      },
    ],
    reviewedAt: '2025-09-25T11:00:00Z',
    createdAt: '2025-09-24T10:00:00Z',
  },
];

export const DEMO_INTEGRATIONS: Integration[] = [
  {
    id: 'int-1',
    websiteId: 'web-1',
    websiteName: 'TechVerse Blog',
    provider: 'wordpress',
    connectionStatus: 'connected',
    siteUrl: 'https://techverse.blog',
    lastSynced: '2025-09-28T15:00:00Z',
    configuration: {
      apiEndpoint: 'https://techverse.blog/wp-json/wp/v2',
      username: 'admin',
      hasCredentials: true,
    },
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'int-2',
    websiteId: 'web-2',
    websiteName: 'HealthWise Hub',
    provider: 'wordpress',
    connectionStatus: 'disconnected',
    siteUrl: 'https://healthwisehub.com',
    configuration: {
      apiEndpoint: 'https://healthwisehub.com/wp-json/wp/v2',
      hasCredentials: false,
    },
    createdAt: '2025-04-15T09:00:00Z',
  },
];

export const DEMO_PUBLISHING_RECORDS: PublishingRecord[] = [
  {
    id: 'pub-1',
    blogId: 'blog-2',
    blogTitle: 'Science-Backed Benefits of Daily Mindfulness Practice',
    provider: 'wordpress',
    publishedUrl: 'https://healthwisehub.com/daily-mindfulness-benefits-science',
    status: 'published',
    publishedAt: '2025-09-27T14:00:00Z',
    createdAt: '2025-09-27T13:50:00Z',
  },
];

export const DEMO_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: 'auto-1',
    websiteId: 'web-1',
    websiteName: 'TechVerse Blog',
    researchFrequency: 'weekly',
    generationFrequency: 'twice_weekly',
    preferredDays: ['Monday', 'Thursday'],
    publishingTime: '09:00',
    maxBlogsPerWeek: 3,
    requireApproval: true,
    status: 'active',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'auto-2',
    websiteId: 'web-2',
    websiteName: 'HealthWise Hub',
    researchFrequency: 'biweekly',
    generationFrequency: 'weekly',
    preferredDays: ['Wednesday'],
    publishingTime: '10:00',
    maxBlogsPerWeek: 2,
    requireApproval: true,
    status: 'paused',
    createdAt: '2025-06-15T10:00:00Z',
    updatedAt: '2025-09-15T10:00:00Z',
  },
];

export const DEMO_ANALYTICS: AnalyticsData = {
  totalBlogs: 47,
  publishedBlogs: 24,
  pendingApproval: 8,
  scheduledBlogs: 5,
  connectedWebsites: 3,
  avgSeoScore: 84,
  avgReadabilityScore: 82,
  blogsByMonth: [
    { month: 'Apr', count: 4 },
    { month: 'May', count: 6 },
    { month: 'Jun', count: 8 },
    { month: 'Jul', count: 7 },
    { month: 'Aug', count: 10 },
    { month: 'Sep', count: 12 },
  ],
  publishingActivity: [
    { date: 'Mon', published: 3, generated: 5 },
    { date: 'Tue', published: 2, generated: 4 },
    { date: 'Wed', published: 4, generated: 6 },
    { date: 'Thu', published: 3, generated: 5 },
    { date: 'Fri', published: 5, generated: 7 },
    { date: 'Sat', published: 1, generated: 2 },
    { date: 'Sun', published: 0, generated: 1 },
  ],
  statusDistribution: [
    { status: 'Published', count: 24 },
    { status: 'Pending', count: 8 },
    { status: 'Draft', count: 6 },
    { status: 'Scheduled', count: 5 },
    { status: 'Approved', count: 4 },
  ],
  topCategories: [
    { category: 'Technology', count: 22 },
    { category: 'Health & Wellness', count: 15 },
    { category: 'Business & Startups', count: 10 },
  ],
};
